#!/usr/bin/sh

killall fuzzel || (cliphist list | fuzzel --dmenu --with-nth 2 fuzzel --log-no-syslog -a top-left --tabs=4 -b 000000cc -t ffffffff -l 10 -B 4 -C 7fc8ffff -w 50 -f "Inter:size=11" | cliphist decode | wl-copy)
