alias dc='docker compose'
alias dcs='docker compose create'
alias dcsta='docker compose start'
alias dcsto='docker compose stop'
alias dcd='docker compose down'
alias dcu='docker compose up -d --no-build'
alias dcb='COMPOSE_BAKE=true docker compose build'
alias dcc='docker buildx prune -af'
alias dcp='docker compose ps -a'
alias di='docker image'
alias ds='docker stats'
alias drm='docker run -it --rm'
alias dcpull='docker compose pull --ignore-pull-failures'
