#!/usr/bin/env sh

killall fuzzel 2>/dev/null && exit 0

# Entries to show in the power menu
choices="Dismiss\nSuspend\nLogout\nReboot\nPoweroff\nSetup"

# Run fuzzel and capture selection
selected=$(printf "%b" "$choices" | fuzzel -d -b 000000cc -t ffffffff -l 10 -B 4 -C 7fc8ffff -f "Inter:size=11" --log-no-syslog -a top-right --hide-prompt --minimal-lines --selection-radius=6 --width 11)

case "$selected" in
    *Dismiss)  makoctl dismiss &&  makoctl reload ;;
    *Logout)   niri msg action quit ;;
    *Reboot)   systemctl reboot ;;
    *Poweroff) systemctl poweroff ;;
    *Suspend)  systemctl suspend ;;
    *Setup)     systemctl reboot --firmware-setup ;;
esac
