#!/usr/bin/env sh
cd ~

if systemctl --user -q is-active niri.service; then
  echo 'A niri session is already running.'
  exit 1
fi

systemctl --user reset-failed
systemctl --user import-environment
if hash dbus-update-activation-environment 2>/dev/null; then
    dbus-update-activation-environment --all
fi

systemctl --user --wait start niri.service
systemctl --user start --job-mode=replace-irreversibly niri-shutdown.target
systemctl --user unset-environment WAYLAND_DISPLAY DISPLAY XDG_SESSION_TYPE XDG_CURRENT_DESKTOP NIRI_SOCKET

#Cleanup
killall -s 2 waybar.sh || true

clear
