#!/usr/bin/env sh

killall fuzzel 2>/dev/null && exit 0

reopen_menu() {
    exec "$0"
}

choices="Applications\nKeyboard\nRotate\nBrightness Up\nBrightness Down\nStack Up\nStack Down\nToggle Stack\nScreenshot"

selected=$(printf "%b" "$choices" | fuzzel -d -b 000000cc -t ffffffff -l 10 -B 4 -C 7fc8ffff -f "Inter:size=14" --line-height=24 --log-no-syslog -a top-left --hide-prompt --minimal-lines --selection-radius=6 --width 16)

confirm_and_run() {
    action="$1"
    message="$2"

    confirm=$(ask_confirm "$message")
    [ "$confirm" = "Yes" ] || return 1
    eval "$action"
}

case "$selected" in
    *Applications)
        ~/git/dotfiles/appmenu_fuzzel
        ;;
    *Keyboard)
        pkill -SIGRTMIN wvkbd-mobintl
        ;;
    *Rotate)
        ~/git/dotfiles/fw12cycle.sh
        reopen_menu
        ;;
    *Brightness\ Up)
        ~/git/dotfiles/br_up.sh
        reopen_menu
        ;;
    *Brightness\ Down)
        ~/git/dotfiles/br_down.sh
        reopen_menu
        ;;
    *Stack\ Up)
        niri msg action focus-window-up
        reopen_menu
        ;;
    *Stack\ Down)
        niri msg action focus-window-down
        reopen_menu
        ;;
    *Toggle\ Stack)
        niri msg action toggle-column-tabbed-display
        reopen_menu
        ;;
    *Screenshot)
        niri msg action screenshot-screen
        ;;
esac
