#!/usr/bin/env sh

killall fuzzel 2>/dev/null && exit 0

reopen_menu() {
    exec "$0" "$@"
}

option="${1:-Applications}"
choices="Power\nApplications\nFiles\nTerminal\nBrowser\nRotate\nKeyboard\nMinimize Bar\nBrightness Up\nBrightness Down\nWorkspace Up\nWorkspace Down\nToggle Stack\nScreenshot\nDismiss notifications"

selected=$(printf "%b" "$choices" | fuzzel -d -b 000000cc -t ffffffff -B 4 -C 7fc8ffff -f "Inter:size=14" --line-height=24 --log-no-syslog -a top-left --hide-prompt --minimal-lines --selection-radius=6 --width 18 --select="$option")

confirm_and_run() {
    action="$1"
    message="$2"

    confirm=$(ask_confirm "$message")
    [ "$confirm" = "Yes" ] || return 1
    eval "$action"
}

case "$selected" in
    *Power)
        ~/git/dotfiles/powermenu_fuzzel
        ;;
    *Applications)
        ~/git/dotfiles/appmenu_fuzzel
        ;;
    *Files)
        nemo
        ;;
    *Terminal)
        alacritty
        ;;
    *Browser)
        helium-browser
        ;;
    *Rotate)
        ~/git/dotfiles/rotate.sh
        ;;
    *Keyboard)
        pkill -SIGRTMIN wvkbd-mobintl
        ;;
    *Minimize\ Bar)
        if [ -e "$HOME/git/dotfiles/waybar/minimal_mode" ]; then
            rm "$HOME/git/dotfiles/waybar/minimal_mode"
        else
            touch "$HOME/git/dotfiles/waybar/minimal_mode"
        fi
        ;;
    *Brightness\ Up)
        ~/git/dotfiles/br_up.sh
        reopen_menu "Brightness Up"
        ;;
    *Brightness\ Down)
        ~/git/dotfiles/br_down.sh
        reopen_menu "Brightness Down"
        ;;
    *Workspace\ Up)
        niri msg action focus-workspace-up
        reopen_menu "Workspace Up"
        ;;
    *Workspace\ Down)
        niri msg action focus-workspace-down
        reopen_menu "Workspace Down"
        ;;
    *Toggle\ Stack)
        niri msg action toggle-column-tabbed-display
        reopen_menu "Toggle Stack"
        ;;
    *Screenshot)
        niri msg action screenshot-screen
        ;;
    *Dismiss\ notifications)
        makoctl dismiss && makoctl reload
        ;;
esac
