#!/usr/bin/env sh

gov=$(cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor \
    | sort | uniq -c | sort -nr | head -n1 | awk '{print $2}')

# Capitalize
gov=$(echo "$gov" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')

if [ -n "$gov" ]; then
    echo "{\"text\":\"$gov\",\"tooltip\":\"Governor: $gov\",\"class\":\"$gov\"}"
else
    echo "{\"text\":\"?\",\"tooltip\":\"failed\"}"
fi
