#!/usr/bin/env sh

gov=$(govctl -G)

# Capitalize
gov=$(echo "$gov" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')

if [ -n "$gov" ]; then
    echo "{\"text\":\"$gov\",\"tooltip\":\"Governor: $gov\",\"class\":\"$gov\"}"
else
    echo "{\"text\":\"?\",\"tooltip\":\"failed\"}"
fi

